
target 'GQDataControllerDemo' do
    pod 'GQDataController', :path => '../'
    pod 'GQDataController/Mantle', :path => '../'

    target 'GQDataControllerDemoTests' do
        pod 'OCMock', '~> 3.2'
    end
end

