
target 'GQDataControllerDemo' do
    pod 'GQDataController', :path => '../'
    pod 'GQDataController/Mantle', :path => '../'
    pod 'GQDataController/YYModel', :path => '../'
    #pod 'GQDataController/YYKit', :path => '../'
    pod 'GQDataController/JSONModel', :path => '../'
    pod 'GQDataController/MJExtension', :path => '../'
    pod 'GQDataController/SQLite', :path => '../'

    target 'GQDataControllerDemoTests' do
        pod 'OCMock', '~> 3.0'
    end
end

